channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - tensorflow-intel==2.18.0
  - tensorflow==2.18.0
name: mlflow-env
